### ISSUE TITLE
does this work?

### ISSUE THREAD

**Issue by Ashishjshetty** [clehner/wpa_state#1]
Hi there, 
I don't think you are maintaining this repo anymore, but did this work for you. I have tried and it didn't work for me. i wrote something of my own to connect to control interface if wpa_supplicant and all i got it to do is connect, i was not able to get it to send any commands. Thanks anyway for this repo.

**Comment by clehner** [comment]
I just tried it and it worked. However, I had to use sudo to get permission to read `/var/run/wpa_supplicant/wlan0`. Also if the network interface goes away, the wpa_supplicant control socket goes away. Are you getting an error?

**Comment by Ashishjshetty** [comment]
It worked, my wpa_supplicant was down due to which it was not working thank you. And when i was trying to write something of my own i didn't attach and tried to send request which wasn't working, used your repo as reference thank you.
